PROGRAM MAIN
  ! subroutines for testing parts of the code
  USE KEYS
  USE CHAINUTIL
  USE GENUTIL
  IMPLICIT NONE
  TYPE(CHAIN), TARGET :: CHAINOBJ
  TYPE(CHAIN), POINTER :: CHAINP

  CHAINP=>CHAINOBJ

  CALL READKEY

  CALL SETUPCHAIN(CHAINP,NBEAD,NFIX)
  CALL SETCHAINPARAMS(CHAINP)
  CALL INITIALIZECHAIN(CHAINP, STARTEQUIL)
  
  !CALL TESTENERGYDERIVS(CHAINP)
  CALL TESTBROWNDYN(CHAINP)

  CALL CLEANUPCHAIN(CHAINP)
CONTAINS
  
  SUBROUTINE TESTBROWNDYN(CHAINP)
    ! test brownian dynamics
    USE BROWNDYN, ONLY : RUNBROWNDYNSIM
    IMPLICIT NONE
    TYPE(CHAIN), POINTER :: CHAINP

    call RUNBROWNDYNSIM(CHAINP, bdSTEPs, DELT,OUTFILE,bdPRINTEVERY,SNAPSHOTFILE,SNAPSHOTEVERY,APPENDSNAPSHOTS,DOBROWN)
  END SUBROUTINE TESTBROWNDYN
  
  SUBROUTINE TESTENERGYDERIVS(CHAINP)
    ! test calculations of energy and its derivatives
    IMPLICIT NONE
    TYPE(CHAIN), POINTER :: CHAINP    
    INTEGER :: I, S
    DOUBLE PRECISION :: ENERGY, ENERGY0
    DOUBLE PRECISION :: FORCES(3,CHAINP%NPT), FORCES0(3,CHAINP%NPT)
    DOUBLE PRECISION, PARAMETER :: TINY=1D-6
    INTEGER :: B
    
    ! output chain snapshot    
    CALL OUTPUTSNAPSHOT(CHAINP,SNAPSHOTFILE,.FALSE.)

    CALL GETCHAINENERGY(CHAINP,ENERGY0,FORCES0,.TRUE.)
    
    ! check derivatives numerically
    DO B = 1,CHAINP%NPT
       DO I = 1,3
          CHAINP%POS(I,B) = CHAINP%POS(I,B) + TINY
          CALL GETCHAINENERGY(CHAINP,ENERGY,FORCES,.FALSE.)
          PRINT*, B, I, -(ENERGY-ENERGY0)/TINY, FORCES0(I,B)
          CHAINP%POS(I,B) = CHAINP%POS(I,B) - TINY
       ENDDO
    ENDDO

    
  END SUBROUTINE TESTENERGYDERIVS
END PROGRAM MAIN
